pipeline {

  agent any

  stages {

    stage('Checkout') {
      steps {
        checkout scm
       
        sh 'scripting/stripper.sh'
        sh 'makeself --target /opt/django minimal terraformation/out.sh bash ./launchersetup.sh'
        
      }

    }

    stage('TF Plan') {
      
      steps {    
      dir('terraformation') {
          sh 'terraform init'
          sh 'terraform plan -out myplan'
          }
      }      
    }
    stage('Publish') {
      steps {
        sh 'aws s3 cp terraformation/out.sh s3://djangoupdater/latest'
      }
    }
    stage('TF Apply') {
      
      steps {
      dir('terraformation') {  
          sh 'terraform apply -input=false myplan'        }
      }
    
  }
  stage('bump version') {
    
   steps {
    dir('terraformation') {
      sh 'asgname=$(terraform show| perl -ne "print \$1 if m#autoScalingGroupName/([^"]+)#"); aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$asgname" --max-size=6 --min-size=6'
      sleep(time:20,unit:"SECONDS")
      sh 'asgname=$(terraform show| perl -ne "print \$1 if m#autoScalingGroupName/([^"]+)#") ; aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$asgname" --max-size=3 --min-size=3'
   }
  }
    }

  }
  } 

