pipeline {

  agent any

  stages {

    stage('Checkout') {
      steps {
        checkout scm
       
        sh 'scripting/stripper.sh'
        sh 'makeself --target /opt/django minimal terraformation/out.sh bash ./launchersetup.sh'
        
      }

    }
    
    stage('unit test') {
      steps {
      sh 'pip install --user requirements.txt'
      sh 'python3 manage.py test'
    }
    }

    stage('TF Plan') {
      
      steps {    
      dir('terraformation') {
          sh 'terraform init'
          sh 'terraform plan -out myplan'
          }
      }      
    }
    stage('Publish') {
      steps {
        sh 'aws s3 cp terraformation/out.sh s3://djangoupdater/latest'
      }
    }
    stage('TF Apply') {
      
      steps {
      dir('terraformation') {  
          sh 'terraform apply -input=false myplan'        }
      }
    
  }
  stage('reload the asg') {
    
   steps {
    dir('terraformation') {
     sh '../scripting/bumpasg.sh'
   }
  }
    }

  }
  } 

